import { NextResponse } from "next/server";
import prisma from "@/lib/db";

export async function GET(
  req: Request,
  { params }: { params: Promise<{ username: string }> },
) {
  try {
    const { username } = await params;

    const profile = await prisma.profile.findUnique({
      where: { username, isPublic: true },
      include: {
        user: {
          select: { email: true },
        },
      },
    });

    if (!profile) {
      return NextResponse.json(
        { error: "Perfil no encontrado" },
        { status: 404 },
      );
    }

    const baseUrl = process.env.NEXTAUTH_URL || "http://localhost:3000";
    const profileUrl = `${baseUrl}/${username}`;

    // Build vCard content
    const vCard = [
      "BEGIN:VCARD",
      "VERSION:3.0",
      `FN:${profile.displayName || profile.username}`,
      `N:${profile.displayName || profile.username};;;`,
      profile.user?.email ? `EMAIL:${profile.user.email}` : "",
      `URL:${profileUrl}`,
      "ORG:BioCard",
      "NOTE:Generated by BioCard",
      "END:VCARD",
    ]
      .filter(Boolean)
      .join("\r\n");

    return new NextResponse(vCard, {
      headers: {
        "Content-Type": "text/vcard",
        "Content-Disposition": `attachment; filename="${username}.vcf"`,
      },
    });
  } catch (error) {
    console.error("Error generating vCard:", error);
    return NextResponse.json(
      { error: "Error al generar vCard" },
      { status: 500 },
    );
  }
}
